module "tenant" {
  source = "../../modules/tenant-module"

  app_name                         = var.app_name
  environment                      = var.environment
  tenant_id                        = var.tenant_id
  pricing_tier                     = var.pricing_tier
  pricing_track                    = var.pricing_track
  aws_region                       = var.aws_region
  app_image_uri                    = var.app_image_uri
  acm_certificate_arn              = var.acm_certificate_arn
  cloudfront_acm_certificate_arn   = var.cloudfront_acm_certificate_arn
  vpc_cidr                         = var.vpc_cidr
  public_subnet_cidrs              = var.public_subnet_cidrs
  private_subnet_cidrs             = var.private_subnet_cidrs
  bucket_suffix                    = var.bucket_suffix
  heartbeat_table_arn              = var.heartbeat_table_arn
  heartbeat_table_name             = var.heartbeat_table_name
  kms_key_arn                      = var.kms_key_arn
  god_mode_enabled                 = var.god_mode_enabled
  god_mode_secret_arn              = var.god_mode_secret_arn
  alert_email                      = var.alert_email
  control_plane_role_arn           = var.control_plane_role_arn
  suspend_threshold_hours_override = var.suspend_threshold_hours_override
  connect_instance_id              = var.connect_instance_id
  cloudfront_enabled               = var.cloudfront_enabled
  waf_enabled                      = var.waf_enabled
  log_retention_days_override      = var.log_retention_days_override
  tags                             = var.tags
}
