# ── Required ──────────────────────────────────────────────────────────────────

variable "app_name" {
  type    = string
  default = "aria"
}

variable "environment" {
  type = string
}

variable "public_url" {
  type        = string
  description = "Public URL of the website (e.g. https://ariaeval.io). Used as NEXTAUTH_URL."
}

# ── Networking ────────────────────────────────────────────────────────────────

variable "vpc_cidr" {
  type    = string
  default = "10.1.0.0/16"
}

variable "public_subnet_cidrs" {
  type    = list(string)
  default = ["10.1.1.0/24", "10.1.2.0/24"]
}

variable "availability_zones" {
  type    = list(string)
  default = ["eu-west-2a", "eu-west-2b"]
}

# ── Container ─────────────────────────────────────────────────────────────────

variable "container_port" {
  type    = number
  default = 3001
}

variable "cpu" {
  type        = number
  default     = 256
  description = "CPU units for Fargate task (256 = 0.25 vCPU)"
}

variable "memory" {
  type        = number
  default     = 512
  description = "Memory MiB for Fargate task"
}

variable "desired_count" {
  type    = number
  default = 1
}

variable "image_tag" {
  type    = string
  default = "latest"
}

variable "image_uri" {
  description = "Full pre-built image URI. When set, overrides ECR repo + image_tag."
  type        = string
  default     = ""
}

# ── Auth secrets ──────────────────────────────────────────────────────────────
# NEXTAUTH_SECRET is auto-generated by random_password.nextauth_secret — no variable needed.
# GOOGLE_CLIENT_ID / GOOGLE_CLIENT_SECRET / GITHUB_CLIENT_ID / GITHUB_CLIENT_SECRET are
# populated out-of-band via the bootstrap script (infra/scripts/bootstrap-oauth-secrets.sh)
# and never stored in tfvars or Terraform state.

variable "cognito_enabled" {
  description = "Whether Cognito is used as the social OAuth broker."
  type        = bool
  default     = false
}

variable "cognito_client_id" {
  description = "Cognito app client ID for NextAuth Cognito provider."
  type        = string
  default     = ""
}

variable "cognito_client_secret" {
  description = "Cognito app client secret for NextAuth Cognito provider."
  type        = string
  sensitive   = true
  default     = ""
}

variable "cognito_issuer" {
  description = "OIDC issuer URL for Cognito user pool."
  type        = string
  default     = ""
}

variable "cognito_domain" {
  description = "Cognito hosted UI domain FQDN."
  type        = string
  default     = ""
}

# ── Control plane ─────────────────────────────────────────────────────────────

variable "control_plane_url" {
  type        = string
  default     = "http://localhost:3002"
  description = "Internal URL of the ARIA control plane API."
}

variable "control_plane_url_ssm_param_name" {
  type        = string
  default     = ""
  description = "Optional SSM Parameter name that stores the control plane URL for runtime discovery."
}

# ── Observability ─────────────────────────────────────────────────────────────

variable "log_retention_days" {
  type    = number
  default = 30
}

variable "enable_container_insights" {
  type    = bool
  default = true
}

# ── Tags ──────────────────────────────────────────────────────────────────────

variable "tags" {
  type    = map(string)
  default = {}
}
